device: cuda
weights:
  doclayout_yolo: Structure/doclayout_yolo_docstructbench_imgsz1280_2501.pt
  layoutreader: Relation
models_dir: model_weight
layout_config: 
  model: doclayout_yolo
  reader:
    name: layoutreader
chat_config:
  weight_path: model_weight/Recognition
  backend: lmdeploy # lmdeploy or transformers
  batch_size: 10 # active when using `transformers` as backend